# Generated by Django 2.2.26 on 2022-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newmod",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
