# Generated by Django 2.2.26 on 2022-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_newmod_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmod',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
