# Generated by Django 2.2.26 on 2022-05-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_newmod_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmod',
            name='phonenumber',
        ),
    ]
