# Generated by Django 2.2.26 on 2022-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rightttt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rightttt",
        ),
    ]
