# Generated by Django 2.2.26 on 2022-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_delete_rightttt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devstring",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
