# Generated by Django 2.2.26 on 2022-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_devstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='rollnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
